name    'puppet-rhnreg_ks'
version '0.0.1'
source 'git://github.com/RedHatEMEA/puppet-rhnreg_ks.git'
author 'Gaël Chamoulaud <gchamoul@redhat.com>'
license 'Apache License, Version 2.0'
summary ''
description 'This module provides Custom Providers for Red Hat Network Registering.'
project_page 'https://github.com/RedHatEMEA/puppet-rhnreg_ks'
