name    'puppet-rhnreg_ks'
version '0.0.1'
source 'git://github.com/strider/puppet-rhnreg_ks.git'
author 'Gaël Chamoulaud <gchamoul@redhat.com>'
license 'Apache License, Version 2.0'
summary 'rhnreg_ks provider for Puppet'
description 'This module provides Custom Providers for Red Hat Network Registering.'
project_page 'https://github.com/strider/puppet-rhnreg_ks'
dependency 'adrienthebo/puppet-boolean', '>=0.9.0'
